# Generated by Django 5.1.6 on 2025-03-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="genre",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
