# Generated by Django 5.1.6 on 2025-03-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0002_album_genre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="album",
            name="cover_url",
        ),
        migrations.RemoveField(
            model_name="album",
            name="release_date",
        ),
        migrations.AddField(
            model_name="album",
            name="release_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="album",
            name="submitted_by",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="album",
            name="genre",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
