# Generated by Django 5.1.6 on 2025-03-21 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0003_remove_album_cover_url_remove_album_release_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="artist",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="album",
            name="genre",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="album",
            name="release_year",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="album",
            name="submitted_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="album",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
