# Generated by Django 4.2.20 on 2025-03-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0005_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="album_art_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="album",
            name="lastfm_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="album",
            name="lastfm_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="album",
            name="mbid",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="album",
            name="release_year",
            field=models.IntegerField(default=0),
        ),
    ]
